from sqlalchemy import Column, Integer, BigInteger, String, Boolean, Text, Float, DateTime, ForeignKey, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship 

Base = declarative_base() 

class Follower(Base):
    __tablename__ = 'followers'
    id = Column(BigInteger, primary_key=True)
    fbid = Column(BigInteger)
    profile_url = Column(String)
    username = Column(String)
    full_name = Column(String, nullable=True)
    follower_count = Column(Integer)
    followees_count = Column(Integer)
    post_count = Column(Integer)
    profile_image_link = Column(String)
    biography = Column(Text, nullable=True)
    biography_hashtags = Column(JSON)
    category_name = Column(String, nullable=True)
    business_category_name = Column(String, nullable=True)
    is_business_account = Column(Boolean)
    is_professional_account = Column(Boolean)
    is_verified = Column(Boolean)
    is_private = Column(Boolean)
    avg_engagement = Column(Float, nullable=True)
    posts = Column(JSON, nullable=True)
    highlight_count = Column(Integer, nullable=True)
    partner_id = Column(Integer, nullable=True)
    email_address = Column(String, nullable=True)
    business_address = Column(JSON, nullable=True)
    related_profiles = Column(JSON, nullable=True)
    external_url = Column(String, nullable=True)
    dorfterror_liked_posts = Column(Integer, default=0)
    dorfterror_comment_count = Column(Integer, default=0)

class Post(Base):
    __tablename__ = 'posts'
    id = Column(BigInteger, primary_key=True)
    shortcode = Column(String)
    user_posted = Column(String)
    date_local = Column(DateTime)
    url = Column(String)
    content_type = Column(String)
    caption = Column(Text, nullable=True)
    caption_hashtags = Column(JSON, nullable=True)
    caption_mentions = Column(JSON, nullable=True)
    tagged_users = Column(JSON, nullable=True)
    video_view_count = Column(Integer, nullable=True)
    video_play_count = Column(Integer, nullable=True)
    video_duration = Column(Float, nullable=True)
    location = Column(JSON, nullable=True)
    media_count = Column(Integer)
    like_count = Column(Integer)
    comment_count = Column(Integer)
    content_type = Column(String)
    post_content = Column(JSON)
    photos = Column(JSON, nullable=True) 
    videos = Column(JSON, nullable=True)
    audio = Column(JSON, nullable=True)
    images = Column(JSON, nullable=True)
    alt_text = Column(Text, nullable=True)
    thumbnail = Column(String, nullable=True)
    product_type = Column(String, nullable=True)
    coauthor_producers = Column(JSON, nullable=True)
    engagement_score_view = Column(Float, nullable=True)
    is_collab = Column(Boolean)
    total_follower_reach = Column(Integer, default=0)

    collaborators = relationship("PostCollaborator", back_populates="post")
    comments = relationship("Comment", back_populates="post")

class PostCollaborator(Base):
    __tablename__ = 'post_collaborators'
    post_id = Column(BigInteger, ForeignKey('posts.id'), primary_key=True)
    user_id = Column(BigInteger, primary_key=True)
    username = Column(String)
    full_name = Column(String)
    follower = Column(Integer)
    posts = Column(Integer)
    avg_engagement = Column(Float, nullable=True)
    
    post = relationship("Post", back_populates="collaborators")
    
class Comment(Base):
    __tablename__ = 'comments'
    id = Column(BigInteger, primary_key=True)
    post_id = Column(BigInteger, ForeignKey('posts.id'))
    parent_comment_id = Column(BigInteger, nullable=True)
    post_url = Column(String)
    user_id = Column(BigInteger, default=None)
    comment_username = Column(String)
    comment_user_url = Column(String)
    replies_count = Column(Integer)
    replied_content = Column(JSON, nullable=True)
    text = Column(Text)
    likes_count = Column(Integer)
    created_at = Column(DateTime)
    hashtags = Column(JSON, nullable=True)
    tags = Column(JSON, nullable=True)
    creator_replied = Column(Boolean, default=False)
    is_follower = Column(Boolean)

    post = relationship("Post", back_populates="comments")